
package nl.kvk.schemas.schemas.hrip.dataservice._2015._02;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DataserviceService", targetNamespace = "http://schemas.kvk.nl/schemas/hrip/dataservice/2015/02", wsdlLocation = "http://schemas.kvk.nl/contracts/kvk/dataservice/catalogus/2015/02/KVK-KvKDataservice.wsdl")
public class DataserviceService
    extends Service
{

    private final static URL DATASERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException DATASERVICESERVICE_EXCEPTION;
    private final static QName DATASERVICESERVICE_QNAME = new QName("http://schemas.kvk.nl/schemas/hrip/dataservice/2015/02", "DataserviceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://schemas.kvk.nl/contracts/kvk/dataservice/catalogus/2015/02/KVK-KvKDataservice.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DATASERVICESERVICE_WSDL_LOCATION = url;
        DATASERVICESERVICE_EXCEPTION = e;
    }

    public DataserviceService() {
        super(__getWsdlLocation(), DATASERVICESERVICE_QNAME);
    }

    public DataserviceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DATASERVICESERVICE_QNAME, features);
    }

    public DataserviceService(URL wsdlLocation) {
        super(wsdlLocation, DATASERVICESERVICE_QNAME);
    }

    public DataserviceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DATASERVICESERVICE_QNAME, features);
    }

    public DataserviceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DataserviceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Dataservice
     */
    @WebEndpoint(name = "DataserviceSoap11")
    public Dataservice getDataserviceSoap11() {
        return super.getPort(new QName("http://schemas.kvk.nl/schemas/hrip/dataservice/2015/02", "DataserviceSoap11"), Dataservice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Dataservice
     */
    @WebEndpoint(name = "DataserviceSoap11")
    public Dataservice getDataserviceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://schemas.kvk.nl/schemas/hrip/dataservice/2015/02", "DataserviceSoap11"), Dataservice.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DATASERVICESERVICE_EXCEPTION!= null) {
            throw DATASERVICESERVICE_EXCEPTION;
        }
        return DATASERVICESERVICE_WSDL_LOCATION;
    }

}
